#!/bin/bash

PATH=~/tools/JLink_Linux_V640b_x86_64:$PATH

BOOTLOADER=build/zero/fk-bootloaders-samd21large.bin

JLinkExe -if SWD -device ATSAMD21G18 <<EOF
exitonerror 1
connect
r
loadfile $BOOTLOADER
r
q
EOF
