#!/bin/bash

ls -alh /dev/tty*modem*

sudo ~/tools/lib/flasher/bossac_osx -d --port=$1 -U -i -e -w -R --offset=16384 blink/build/blink.bin

# sudo ~/tools/lib/flasher/bossac_linux -d --port=$1 -U -i -e -w -R --offset=16384 blink/build/blink.bin
