#!/bin/bash

PATH=~/tools/jlink:$PATH

BOOTLOADER=fk-bootloaders-samd21large.bin

if [ ! -f $BOOTLOADER ]; then
    BOOTLOADER=build/zero/fk-bootloaders-samd21large.bin
fi

if [ ! -f $BOOTLOADER ]; then
    echo "Missing bootloader firmware"
    exit
fi

TEST=fk-core-test.bin

if [ ! -f $TEST ]; then
    TEST=../core/build/firmware/test/fk-core-test.bin
fi

if [ ! -f $TEST ]; then
    echo "Missing test firmware"
    exit
fi

JLinkExe -if SWD -device ATSAMD21G18 -speed 4000 <<EOF
exitonerror 1
connect
sleep 100
r
sleep 100
loadfile $BOOTLOADER
sleep 100
loadfile $TEST,0x8000
r
q
EOF
