#!/bin/bash

UNAME=`uname`

if [[ "$UNAME" == "Linux" ]]; then
    sudo ~/tools/lib/flasher/bossac_linux -d --port=$1 -U -i -e -w -R --offset=16384 blink/build/blink.bin
fi

if [[ "$UNAME" == "Darwin" ]]; then
    ls -alh /dev/tty*modem*
    sudo ~/tools/lib/flasher/bossac_osx -d --port=$1 -U -i -e -w -R --offset=16384 blink/build/blink.bin
fi
